[build]
  command = "npm run build"  # Adjust this to your build script
  publish = "build"          # Adjust this to your build output directory

# If you're using client-side routing (e.g., with React Router), add redirects
[[redirects]]
  from = "/*"
  to = "/registerform.html"
  status = 200
